# Generated by Django 4.1.3 on 2022-11-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name'),
        ('users', '0004_auto_20221117_1434'),
    ]

    operations = [
    ]
