# Generated by Django 2.2.16 on 2022-11-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221115_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
