# Generated by Django 4.1.3 on 2022-11-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rating_titles_rating_user_titles_rating1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='Rating1',
            new_name='Rating',
        ),
    ]
