# Generated by Django 4.1.3 on 2022-11-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_rating1_titles_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='Rating',
            new_name='rating',
        ),
    ]
