# Generated by Django 4.1.3 on 2022-11-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_rename_rating_titles_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='titles',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
