# Generated by Django 4.1.3 on 2022-11-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_comment_review_delete_rating_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, to='reviews.genres', verbose_name='жанр'),
        ),
    ]
