# Generated by Django 2.2.16 on 2022-11-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20221119_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
