# Generated by Django 2.2.16 on 2022-11-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_auto_20221121_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
