# Generated by Django 2.2.16 on 2022-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20221121_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='title', to='reviews.Genre', verbose_name='жанр'),
        ),
    ]
