# Generated by Django 2.2.16 on 2022-11-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_auto_20221121_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'ordering': ['-pub_date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
